version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.2.0
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Running pre-build steps...
  build:
    commands:
      - echo Building the Vite React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://notquitebucket --delete
artifacts:
  files:
    - "**/*"
  base-directory: dist
cache:
  paths:
    - node_modules/**/*
