version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.2.0
    commands:
      - echo Installing dependencies...
      - npm cache clean --force
      - npm config set registry=https://registry.npmjs.org/
      - npm i --verbose
  pre_build:
    commands:
      - echo Running pre-build steps...
      - sudo ulimit -n unlimited
      - echo Downloading aws-exports.ts from S3...
      - aws s3 cp s3://notquitebucket/aws-exports.ts ./src/aws-exports.ts

  build:
    commands:
      - echo Building the Vite React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://notquitebucket --delete --exclude "aws-exports.ts"
artifacts:
  files:
    - "**/*"
  base-directory: dist
cache:
  paths:
    - node_modules/**/*
