DROP TABLE IF EXISTS events;

CREATE TABLE events(
    id serial PRIMARY KEY,
    title varchar(255) NOT NULL,
    location varchar(255),
    description text,
    cognito_user_id varchar(255),
    date timestamp,
    image varchar(255),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    last_updated timestamp DEFAULT CURRENT_TIMESTAMP,
    cancelled boolean DEFAULT FALSE,
    maxAttendees int
);

INSERT INTO events(title, location, description, cognito_user_id, date, image, created_at, last_updated, cancelled, maxAttendees)
    VALUES ('Acrobatics Performance', 'Gymnasium A', 'Join us for an exciting acrobatics performance.', 'cognito-user-1', '2024-09-01 10:00:00', 'src/images/acrobatics.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30),
('Archery Competition', 'Archery Range B', 'Test your archery skills in this competition.', 'cognito-user-1', '2024-09-02 11:00:00', 'src/images/archery.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Artistic Swimming Showcase', 'Aquatic Center C', 'Watch amazing routines in artistic swimming.', 'cognito-user-1', '2024-09-03 12:00:00', 'src/images/artistic_swimming.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Track Meet', 'Track Field D', 'Compete in various track and field events.', 'cognito-user-1', '2024-09-04 09:00:00', 'src/images/track.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40),
('Badminton Tournament', 'Sports Hall E', 'Join the badminton tournament and showcase your skills.', 'cognito-user-1', '2024-09-05 14:00:00', 'src/images/badminton.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Baseball/Softball Game', 'Baseball Field F', 'Enjoy a thrilling baseball/softball game.', 'cognito-user-1', '2024-09-06 16:00:00', 'src/images/baseball_softball.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50),
('Basketball Pick-Up Game', 'Basketball Court G', 'Come join a casual pick-up basketball game.', 'cognito-user-1', '2024-09-07 18:00:00', 'src/images/basketball.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30),
('Handball Match', 'Indoor Arena H', 'Participate in an exciting handball match.', 'cognito-user-1', '2024-09-08 19:00:00', 'src/images/handball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Volleyball Tournament', 'Beach Volleyball Court I', 'Join the volleyball tournament at the beach.', 'cognito-user-1', '2024-09-09 10:00:00', 'src/images/volleyball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Biathlon Challenge', 'Ski Resort J', 'Take part in a biathlon challenge combining skiing and shooting.', 'cognito-user-1', '2024-09-10 07:00:00', 'src/images/biathlon.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Bobsleigh Race', 'Bobsleigh Track K', 'Experience the thrill of bobsleigh racing.', 'cognito-user-1', '2024-09-11 13:00:00', 'src/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40),
('Boxing Tournament', 'Boxing Gym L', 'Watch intense boxing matches in the tournament.', 'cognito-user-1', '2024-09-12 15:00:00', 'src/images/boxing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Break Dancing Battle', 'Dance Studio M', 'Show off your break dancing skills in this battle.', 'cognito-user-1', '2024-09-13 17:00:00', 'src/images/break_dancing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Canoe Regatta', 'Lake N', 'Participate in an exciting canoe regatta.', 'cognito-user-1', '2024-09-14 09:00:00', 'src/images/canoe.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10),
('Cricket Match', 'Cricket Ground O', 'Join the cricket match and enjoy the game.', 'cognito-user-1', '2024-09-15 12:00:00', 'src/images/cricket.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30),
('Curling Event', 'Curling Rink P', 'Test your skills in this curling event.', 'cognito-user-1', '2024-09-16 14:00:00', 'src/images/curling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Cycling Race', 'Cycling Track Q', 'Race in a thrilling cycling competition.', 'cognito-user-1', '2024-09-17 08:00:00', 'src/images/cycling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 45),
('Diving Competition', 'Diving Pool R', 'Compete in a diving competition.', 'cognito-user-1', '2024-09-18 10:00:00', 'src/images/diving.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Equestrian Show', 'Equestrian Center S', 'Enjoy a beautiful equestrian show.', 'cognito-user-1', '2024-09-19 11:00:00', 'src/images/equestrian.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35),
('Fencing Tournament', 'Fencing Hall T', 'Participate in a fencing tournament.', 'cognito-user-1', '2024-09-20 13:00:00', 'src/images/fencing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10),
('Figure Skating Gala', 'Ice Rink U', 'Watch stunning figure skating performances.', 'cognito-user-1', '2024-09-21 14:00:00', 'src/images/figure_skating.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30),
('Flag Football Game', 'Football Field V', 'Join a fun flag football game.', 'cognito-user-1', '2024-09-22 15:00:00', 'src/images/flag_football.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Soccer Match', 'Soccer Field W', 'Participate in an exciting soccer match.', 'cognito-user-1', '2024-09-23 16:00:00', 'src/images/soccer.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50),
('Golf Tournament', 'Golf Course X', 'Join the golf tournament and showcase your skills.', 'cognito-user-1', '2024-09-24 17:00:00', 'src/images/golf.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Hockey Game', 'Ice Rink Y', 'Enjoy a thrilling hockey game.', 'cognito-user-1', '2024-09-25 18:00:00', 'src/images/hockey.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40),
('Judo Contest', 'Judo Arena Z', 'Compete in a judo contest.', 'cognito-user-1', '2024-09-26 19:00:00', 'src/images/judo.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Karate Championship', 'Karate Dojo AA', 'Show your karate skills in this championship.', 'cognito-user-1', '2024-09-27 20:00:00', 'src/images/karate.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Lacrosse Game', 'Lacrosse Field BB', 'Join the lacrosse game and have fun.', 'cognito-user-1', '2024-09-28 21:00:00', 'src/images/lax.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Luge Race', 'Luge Track CC', 'Experience the thrill of luge racing.', 'cognito-user-1', '2024-09-29 22:00:00', 'src/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35),
('Pentathlon Event', 'Pentathlon Venue DD', 'Participate in an exciting pentathlon event.', 'cognito-user-1', '2024-09-30 23:00:00', 'src/images/triathlon.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50),
('Roller Skating Competition', 'Roller Rink EE', 'Enjoy a roller skating competition.', 'cognito-user-1', '2024-10-01 09:00:00', 'src/images/roller_skate.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Rowing Regatta', 'Rowing Dock FF', 'Compete in a thrilling rowing regatta.', 'cognito-user-1', '2024-10-02 10:00:00', 'src/images/rowing.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 45),
('Rugby Match', 'Rugby Field GG', 'Join the rugby match and enjoy the game.', 'cognito-user-1', '2024-10-03 11:00:00', 'src/images/rugby.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Sailing Regatta', 'Marina HH', 'Participate in an exciting sailing regatta.', 'cognito-user-1', '2024-10-04 12:00:00', 'src/images/sailing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35),
('Shooting Contest', 'Shooting Range II', 'Test your aim in this shooting contest.', 'cognito-user-1', '2024-10-05 13:00:00', 'src/images/shooting.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Ski Jumping Event', 'Ski Jumping Hill JJ', 'Experience the thrill of ski jumping.', 'cognito-user-1', '2024-10-06 14:00:00', 'src/images/ski.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Snowboarding Competition', 'Snowboard Park KK', 'Show off your snowboarding skills.', 'cognito-user-1', '2024-10-07 15:00:00', 'src/images/snowboarding.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50),
('Speed Skating Race', 'Speed Skating Oval LL', 'Compete in a fast-paced speed skating race.', 'cognito-user-1', '2024-10-08 16:00:00', 'src/images/speed_skating.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Sport Climbing Challenge', 'Climbing Gym MM', 'Take on the sport climbing challenge.', 'cognito-user-1', '2024-10-09 17:00:00', 'src/images/climbing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35),
('Surfing Competition', 'Surf Beach NN', 'Ride the waves in this surfing competition.', 'cognito-user-1', '2024-10-10 18:00:00', 'src/images/surfing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Swimming Meet', 'Swimming Pool OO', 'Compete in various swimming events.', 'cognito-user-1', '2024-10-11 19:00:00', 'src/images/swimming.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30),
('Table Tennis Tournament', 'Table Tennis Hall PP', 'Join the table tennis tournament.', 'cognito-user-1', '2024-10-12 20:00:00', 'src/images/table_tennis.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10),
('Taekwondo Championship', 'Taekwondo Dojo QQ', 'Show your taekwondo skills in this championship.', 'cognito-user-1', '2024-10-13 21:00:00', 'src/images/taekwondo.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Tennis Match', 'Tennis Court RR', 'Enjoy a competitive tennis match.', 'cognito-user-1', '2024-10-14 22:00:00', 'src/images/tennis.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25),
('Trampoline Showcase', 'Gymnasium SS', 'Watch amazing trampoline routines.', 'cognito-user-1', '2024-10-15 09:00:00', 'src/images/trampoline.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35),
('Triathlon Race', 'Triathlon Course TT', 'Compete in a challenging triathlon race.', 'cognito-user-1', '2024-10-16 10:00:00', 'src/images/triathlon.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15),
('Weightlifting Competition', 'Weightlifting Gym UU', 'Show off your strength in this weightlifting competition.', 'cognito-user-1', '2024-10-17 11:00:00', 'src/images/weightlifting.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20),
('Wrestling Match', 'Wrestling Arena VV', 'Watch intense wrestling matches.', 'cognito-user-1', '2024-10-18 12:00:00', 'src/images/wrestling.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50),
('Wushu Event', 'Martial Arts Hall ZZ', 'Experience the art of wushu in this event.', 'cognito-user-1', '2024-10-22 15:00:00', 'src/images/wushu.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10);

