DROP TABLE IF EXISTS events;

CREATE TABLE events(
    id serial PRIMARY KEY,
    title varchar(255) NOT NULL,
    location varchar(255),
    description text,
    cognito_user_id varchar(255),
    date timestamp,
    image varchar(255),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    last_updated timestamp DEFAULT CURRENT_TIMESTAMP,
    cancelled boolean DEFAULT FALSE,
    max_attendees int NOT NULL,
    sport varchar(255) NOT NULL
);

CREATE TABLE event_attendees(
    id serial PRIMARY KEY,
    event_id int NOT NULL,
    cognito_user_id varchar(255) NOT NULL,
    joined_at timestamp DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT unique_event_user UNIQUE (event_id, cognito_user_id)
);

INSERT INTO events(title, location, description, cognito_user_id, date, image, created_at, last_updated, cancelled, max_attendees, sport)
    VALUES ('Acrobatics Performance', 'Gymnasium A', 'Join us for an exciting acrobatics performance.', 'cognito-user-1', '2024-09-01 10:00:00', ' /images/acrobatics.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30, 'Acrobatics'),
('Archery Competition', 'Archery Range B', 'Test your archery skills in this competition.', 'cognito-user-1', '2024-09-02 11:00:00', ' /images/archery.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Archery'),
('Artistic Swimming Showcase', 'Aquatic Center C', 'Watch amazing routines in artistic swimming.', 'cognito-user-1', '2024-09-03 12:00:00', '/images/artistic_swimming.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Artistic Swimming'),
('Track Meet', 'Track Field D', 'Compete in various track and field events.', 'cognito-user-1', '2024-09-04 09:00:00', '/images/track.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40, 'Track and Field'),
('Badminton Tournament', 'Sports Hall E', 'Join the badminton tournament and showcase your skills.', 'cognito-user-1', '2024-09-05 14:00:00', '/images/badminton.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Badminton'),
('Baseball/Softball Game', 'Baseball Field F', 'Enjoy a thrilling baseball/softball game.', 'cognito-user-1', '2024-09-06 16:00:00', '/images/baseball_softball.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50, 'Baseball/Softball'),
('Basketball Pick-Up Game', 'Basketball Court G', 'Come join a casual pick-up basketball game.', 'cognito-user-1', '2024-09-07 18:00:00', '/images/basketball.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30, 'Basketball'),
('Handball Match', 'Indoor Arena H', 'Participate in an exciting handball match.', 'cognito-user-1', '2024-09-08 19:00:00', '/images/handball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Handball'),
('Volleyball Tournament', 'Beach Volleyball Court I', 'Join the volleyball tournament at the beach.', 'cognito-user-1', '2024-09-09 10:00:00', '/images/volleyball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Volleyball'),
('Biathlon Challenge', 'Ski Resort J', 'Take part in a biathlon challenge combining skiing and shooting.', 'cognito-user-1', '2024-09-10 07:00:00', '/images/biathlon.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Biathlon'),
('Bobsleigh Race', 'Bobsleigh Track K', 'Experience the thrill of bobsleigh racing.', 'cognito-user-1', '2024-09-11 13:00:00', '/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40, 'Bobsleigh'),
('Boxing Tournament', 'Boxing Gym L', 'Watch intense boxing matches in the tournament.', 'cognito-user-1', '2024-09-12 15:00:00', '/images/boxing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Boxing'),
('Break Dancing Battle', 'Dance Studio M', 'Show off your break dancing skills in this battle.', 'cognito-user-1', '2024-09-13 17:00:00', '/images/break_dancing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Break Dancing'),
('Canoe Regatta', 'Lake N', 'Participate in an exciting canoe regatta.', 'cognito-user-1', '2024-09-14 09:00:00', '/images/canoe.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10, 'Canoe'),
('Cricket Match', 'Cricket Ground O', 'Join the cricket match and enjoy the game.', 'cognito-user-1', '2024-09-15 12:00:00', '/images/cricket.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30, 'Cricket'),
('Curling Event', 'Curling Rink P', 'Test your skills in this curling event.', 'cognito-user-1', '2024-09-16 14:00:00', '/images/curling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Curling'),
('Cycling Race', 'Cycling Track Q', 'Race in a thrilling cycling competition.', 'cognito-user-1', '2024-09-17 08:00:00', '/images/cycling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 45, 'Cycling'),
('Diving Competition', 'Diving Pool R', 'Compete in a diving competition.', 'cognito-user-1', '2024-09-18 10:00:00', '/images/diving.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Diving'),
('Equestrian Show', 'Equestrian Center S', 'Enjoy a beautiful equestrian show.', 'cognito-user-1', '2024-09-19 11:00:00', '/images/equestrian.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35, 'Equestrian'),
('Fencing Tournament', 'Fencing Hall T', 'Participate in a fencing tournament.', 'cognito-user-1', '2024-09-20 13:00:00', '/images/fencing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10, 'Fencing'),
('Figure Skating Gala', 'Ice Rink U', 'Watch stunning figure skating performances.', 'cognito-user-1', '2024-09-21 14:00:00', '/images/figure_skating.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30, 'Figure Skating'),
('Flag Football Game', 'Football Field V', 'Join a fun flag football game.', 'cognito-user-1', '2024-09-22 15:00:00', '/images/flag_football.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Flag Football'),
('Soccer Match', 'Soccer Field W', 'Participate in an exciting soccer match.', 'cognito-user-1', '2024-09-23 16:00:00', '/images/soccer.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50, 'Soccer'),
('Golf Tournament', 'Golf Course X', 'Join the golf tournament and showcase your skills.', 'cognito-user-1', '2024-09-24 17:00:00', '/images/golf.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Golf'),
('Hockey Game', 'Ice Rink Y', 'Enjoy a thrilling hockey game.', 'cognito-user-1', '2024-09-25 18:00:00', '/images/hockey.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 40, 'Hockey'),
('Judo Contest', 'Judo Arena Z', 'Compete in a judo contest.', 'cognito-user-1', '2024-09-26 19:00:00', '/images/judo.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Judo'),
('Karate Championship', 'Karate Dojo AA', 'Show your karate skills in this championship.', 'cognito-user-1', '2024-09-27 20:00:00', '/images/karate.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Karate'),
('Lacrosse Game', 'Lacrosse Field BB', 'Join the lacrosse game and have fun.', 'cognito-user-1', '2024-09-28 21:00:00', '/images/lax.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Lacrosse'),
('Luge Race', 'Luge Track CC', 'Experience the thrill of luge racing.', 'cognito-user-1', '2024-09-29 22:00:00', '/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35, 'Luge'),
('Pentathlon Event', 'Pentathlon Venue DD', 'Participate in an exciting pentathlon event.', 'cognito-user-1', '2024-09-30 23:00:00', '/images/triathlon.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50, 'Pentathlon'),
('Roller Skating Competition', 'Roller Rink EE', 'Enjoy a roller skating competition.', 'cognito-user-1', '2024-10-01 09:00:00', '/images/roller_skate.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Roller Skating'),
('Rowing Regatta', 'Rowing Dock FF', 'Compete in a thrilling rowing regatta.', 'cognito-user-1', '2024-10-02 10:00:00', '/images/rowing.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 45, 'Rowing'),
('Rugby Match', 'Rugby Field GG', 'Join the rugby match and enjoy the game.', 'cognito-user-1', '2024-10-03 11:00:00', '/images/rugby.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Rugby'),
('Sailing Regatta', 'Marina HH', 'Participate in an exciting sailing regatta.', 'cognito-user-1', '2024-10-04 12:00:00', '/images/sailing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35, 'Sailing'),
('Shooting Contest', 'Shooting Range II', 'Test your aim in this shooting contest.', 'cognito-user-1', '2024-10-05 13:00:00', '/images/shooting.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Shooting'),
('Ski Jumping Event', 'Ski Jumping Hill JJ', 'Experience the thrill of ski jumping.', 'cognito-user-1', '2024-10-06 14:00:00', '/images/ski.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Ski Jumping'),
('Snowboarding Competition', 'Snowboard Park KK', 'Show off your snowboarding skills.', 'cognito-user-1', '2024-10-07 15:00:00', '/images/snowboarding.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50, 'Snowboarding'),
('Speed Skating Race', 'Speed Skating Oval LL', 'Compete in a fast-paced speed skating race.', 'cognito-user-1', '2024-10-08 16:00:00', '/images/speed_skating.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Speed Skating'),
('Sport Climbing Challenge', 'Climbing Gym MM', 'Take on the sport climbing challenge.', 'cognito-user-1', '2024-10-09 17:00:00', '/images/climbing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35, 'Sport Climbing'),
('Surfing Competition', 'Surf Beach NN', 'Ride the waves in this surfing competition.', 'cognito-user-1', '2024-10-10 18:00:00', '/images/surfing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Surfing'),
('Swimming Meet', 'Swimming Pool OO', 'Compete in various swimming events.', 'cognito-user-1', '2024-10-11 19:00:00', '/images/swimming.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 30, 'Swimming'),
('Table Tennis Tournament', 'Table Tennis Hall PP', 'Join the table tennis tournament.', 'cognito-user-1', '2024-10-12 20:00:00', '/images/table_tennis.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10, 'Table Tennis'),
('Taekwondo Championship', 'Taekwondo Dojo QQ', 'Show your taekwondo skills in this championship.', 'cognito-user-1', '2024-10-13 21:00:00', '/images/taekwondo.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Taekwondo'),
('Tennis Match', 'Tennis Court RR', 'Enjoy a competitive tennis match.', 'cognito-user-1', '2024-10-14 22:00:00', '/images/tennis.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 25, 'Tennis'),
('Trampoline Showcase', 'Gymnasium SS', 'Watch amazing trampoline routines.', 'cognito-user-1', '2024-10-15 09:00:00', '/images/trampoline.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 35, 'Trampoline'),
('Triathlon Race', 'Triathlon Course TT', 'Compete in a challenging triathlon race.', 'cognito-user-1', '2024-10-16 10:00:00', '/images/triathlon.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 15, 'Triathlon'),
('Weightlifting Competition', 'Weightlifting Gym UU', 'Show off your strength in this weightlifting competition.', 'cognito-user-1', '2024-10-17 11:00:00', '/images/weightlifting.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 20, 'Weightlifting'),
('Wrestling Match', 'Wrestling Arena VV', 'Watch intense wrestling matches.', 'cognito-user-1', '2024-10-18 12:00:00', '/images/wrestling.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 50, 'Wrestling'),
('Wushu Event', 'Martial Arts Hall ZZ', 'Experience the art of wushu in this event.', 'cognito-user-1', '2024-10-22 15:00:00', '/images/wushu.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 10, 'Wushu');

