INSERT INTO events(title, location, description, cognito_user_id, date, image, created_at, last_updated, cancelled)
    VALUES ('Acrobatics Performance', 'Gymnasium A', 'Join us for an exciting acrobatics performance.', 'cognito-user-1', '2024-09-01 10:00:00', 'src/images/acrobatics.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Archery Competition', 'Archery Range B', 'Test your archery skills in this competition.', 'cognito-user-1', '2024-09-02 11:00:00', 'src/images/archery.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Artistic Swimming Showcase', 'Aquatic Center C', 'Watch amazing routines in artistic swimming.', 'cognito-user-1', '2024-09-03 12:00:00', 'src/images/artistic_swimming.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Track Meet', 'Track Field D', 'Compete in various track and field events.', 'cognito-user-1', '2024-09-04 09:00:00', 'images/track.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Badminton Tournament', 'Sports Hall E', 'Join the badminton tournament and showcase your skills.', 'cognito-user-1', '2024-09-05 14:00:00', 'src/images/badminton.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Baseball/Softball Game', 'Baseball Field F', 'Enjoy a thrilling baseball/softball game.', 'cognito-user-1', '2024-09-06 16:00:00', 'src/images/baseball_softball.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Basketball Pick-Up Game', 'Basketball Court G', 'Come join a casual pick-up basketball game.', 'cognito-user-1', '2024-09-07 18:00:00', 'src/images/basketball.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Handball Match', 'Indoor Arena H', 'Participate in an exciting handball match.', 'cognito-user-1', '2024-09-08 19:00:00', 'src/images/handball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Volleyball Tournament', 'Beach Volleyball Court I', 'Join the volleyball tournament at the beach.', 'cognito-user-1', '2024-09-09 10:00:00', 'src/images/volleyball.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Biathlon Challenge', 'Ski Resort J', 'Take part in a biathlon challenge combining skiing and shooting.', 'cognito-user-1', '2024-09-10 07:00:00', 'src/images/biathlon.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Bobsleigh Race', 'Bobsleigh Track K', 'Experience the thrill of bobsleigh racing.', 'cognito-user-1', '2024-09-11 13:00:00', 'src/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Boxing Tournament', 'Boxing Gym L', 'Watch intense boxing matches in the tournament.', 'cognito-user-1', '2024-09-12 15:00:00', 'src/images/boxing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Break Dancing Battle', 'Dance Studio M', 'Show off your break dancing skills in this battle.', 'cognito-user-1', '2024-09-13 17:00:00', 'src/images/break_dancing.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Canoe Regatta', 'Lake N', 'Participate in an exciting canoe regatta.', 'cognito-user-1', '2024-09-14 09:00:00', 'src/images/canoe.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Cricket Match', 'Cricket Ground O', 'Join the cricket match and enjoy the game.', 'cognito-user-1', '2024-09-15 12:00:00', 'src/images/cricket.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Curling Event', 'Curling Rink P', 'Test your skills in this curling event.', 'cognito-user-1', '2024-09-16 14:00:00', 'src/images/curling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Cycling Race', 'Cycling Track Q', 'Race in a thrilling cycling competition.', 'cognito-user-1', '2024-09-17 08:00:00', 'src/images/cycling.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Diving Competition', 'Diving Pool R', 'Compete in a diving competition.', 'cognito-user-1', '2024-09-18 10:00:00', 'src/images/diving.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Equestrian Show', 'Equestrian Center S', 'Enjoy a beautiful equestrian show.', 'cognito-user-1', '2024-09-19 11:00:00', 'src/images/equestrian.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Fencing Tournament', 'Fencing Hall T', 'Participate in a fencing tournament.', 'cognito-user-1', '2024-09-20 13:00:00', 'src/images/fencing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Figure Skating Gala', 'Ice Rink U', 'Watch stunning figure skating performances.', 'cognito-user-1', '2024-09-21 14:00:00', 'src/images/figure_skating.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Flag Football Game', 'Football Field V', 'Join a fun flag football game.', 'cognito-user-1', '2024-09-22 15:00:00', 'src/images/flag_football.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Soccer Match', 'Soccer Field W', 'Participate in an exciting soccer match.', 'cognito-user-1', '2024-09-23 16:00:00', 'src/images/soccer.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Golf Tournament', 'Golf Course X', 'Join the golf tournament and showcase your skills.', 'cognito-user-1', '2024-09-24 17:00:00', 'src/images/golf.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Hockey Game', 'Ice Rink Y', 'Enjoy a thrilling hockey game.', 'cognito-user-1', '2024-09-25 18:00:00', 'src/images/hockey.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Judo Contest', 'Judo Arena Z', 'Compete in a judo contest.', 'cognito-user-1', '2024-09-26 19:00:00', 'src/images/judo.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Karate Championship', 'Karate Dojo AA', 'Show your karate skills in this championship.', 'cognito-user-1', '2024-09-27 20:00:00', 'src/images/karate.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Lacrosse Game', 'Lacrosse Field BB', 'Join the lacrosse game and have fun.', 'cognito-user-1', '2024-09-28 21:00:00', 'src/images/lax.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Luge Race', 'Luge Track CC', 'Experience the thrill of luge racing.', 'cognito-user-1', '2024-09-29 22:00:00', 'src/images/bobsleigh.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Pentathlon Event', 'Pentathlon Venue DD', 'Participate in an exciting pentathlon event.', 'cognito-user-1', '2024-09-30 23:00:00', 'src/images/pentathlon.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Roller Skating Competition', 'Roller Rink EE', 'Enjoy a roller skating competition.', 'cognito-user-1', '2024-10-01 09:00:00', 'src/images/roller_skate.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Rowing Regatta', 'Rowing Dock FF', 'Compete in a thrilling rowing regatta.', 'cognito-user-1', '2024-10-02 10:00:00', 'src/images/rowing.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Rugby Match', 'Rugby Field GG', 'Join the rugby match and enjoy the game.', 'cognito-user-1', '2024-10-03 11:00:00', 'src/images/rugby.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Sailing Race', 'Sailing Marina HH', 'Participate in a sailing race.', 'cognito-user-1', '2024-10-04 12:00:00', 'src/images/sailing.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Shooting Competition', 'Shooting Range II', 'Compete in a shooting competition.', 'cognito-user-1', '2024-10-05 13:00:00', 'src/images/shooting.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Skateboarding Event', 'Skate Park JJ', 'Show off your skateboarding skills in this event.', 'cognito-user-1', '2024-10-06 14:00:00', 'src/images/skateboarding.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Skeleton Race', 'Skeleton Track KK', 'Experience the thrill of skeleton racing.', 'cognito-user-1', '2024-10-07 15:00:00', 'src/images/skeleton.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Skiing Event', 'Ski Resort LL', 'Join the skiing event and enjoy the slopes.', 'cognito-user-1', '2024-10-08 16:00:00', 'src/images/aplineskii.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Snowboarding Competition', 'Snowboarding Park MM', 'Compete in a snowboarding competition.', 'cognito-user-1', '2024-10-09 17:00:00', 'src/images/snowboarding.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Climbing Challenge', 'Climbing Wall NN', 'Test your climbing skills in this challenge.', 'cognito-user-1', '2024-10-10 18:00:00', 'src/images/climbing.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Squash Tournament', 'Squash Court OO', 'Participate in a squash tournament.', 'cognito-user-1', '2024-10-11 19:00:00', 'src/images/squash.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Surfing Competition', 'Surf Beach PP', 'Join a thrilling surfing competition.', 'cognito-user-1', '2024-10-12 20:00:00', 'src/images/surfing.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Swimming Meet', 'Swimming Pool QQ', 'Compete in a swimming meet.', 'cognito-user-1', '2024-10-13 21:00:00', 'src/images/swimming.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Table Tennis Tournament', 'Table Tennis Hall RR', 'Participate in a table tennis tournament.', 'cognito-user-1', '2024-10-14 22:00:00', 'src/images/table_tennis.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Tennis Match', 'Tennis Court SS', 'Join a competitive tennis match.', 'cognito-user-1', '2024-10-15 23:00:00', 'src/images/tennis.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Tae Kwon Do Championship', 'Martial Arts Center TT', 'Show your tae kwon do skills in this championship.', 'cognito-user-1', '2024-10-16 09:00:00', 'src/images/tae_kwon_do.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Trampoline Event', 'Trampoline Park UU', 'Enjoy a fun trampoline event.', 'cognito-user-1', '2024-10-17 10:00:00', 'src/images/trampoline.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Triathlon Race', 'Triathlon Course VV', 'Compete in a challenging triathlon race.', 'cognito-user-1', '2024-10-18 11:00:00', 'src/images/triathlon.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Water Polo Match', 'Water Polo Arena WW', 'Join an exciting water polo match.', 'cognito-user-1', '2024-10-19 12:00:00', 'src/images/water_polo.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Weightlifting Competition', 'Weightlifting Gym XX', 'Participate in a weightlifting competition.', 'cognito-user-1', '2024-10-20 13:00:00', 'src/images/weightlifting.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Wrestling Match', 'Wrestling Arena YY', 'Enjoy an intense wrestling match.', 'cognito-user-1', '2024-10-21 14:00:00', 'src/images/wrestling.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
('Wushu Event', 'Martial Arts Hall ZZ', 'Experience the art of wushu in this event.', 'cognito-user-1', '2024-10-22 15:00:00', 'src/images/wushu.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE);

