export const sports = [
  "Acrobatics",
  "Archery",
  "Artistic Swimming",
  "Track",
  "Badminton",
  "Baseball",
  "Basketball",
  "Handball",
  "Volleyball",
  "Biathlon",
  "Bobsleigh",
  "Boxing",
  "Break Dancing",
  "Canoe",
  "Cricket",
  "Curling",
  "Cycling",
  "Diving",
  "Equestrian",
  "Fencing",
  "Figure Skating",
  "Flag Football",
  "Soccer",
  "Golf",
  "Hockey",
  "Judo",
  "Karate",
  "Lacrosse",
  "Luge",
  "Pentathlon",
  "Roller Skating",
  "Rowing",
  "Rugby",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Skeleton",
  "Ski",
  "Snowboard",
  "Climbing",
  "Squash",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Tae Kwon Do",
  "Trampoline",
  "Triathlon",
  "Water Polo",
  "Weightlifting",
  "Wrestling",
  "Wushu",
];
